# Site settings
title: MQ
email: shmao288@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mqsh.me" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  mq380
weibo:    loveatline4
github:   mq-380
#codepen:  username
#dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
<<<<<<< HEAD
sass:
  style: compressed
gems:
  - jekyll-sitemap
=======
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: MaoQ
  email: shmao288@gmail.com
  
# Social account
  twitter: mq380
  github:  mq-380
  facebook: quan.mao.9
  weibo: loveatline4

# 站点信息
title: MQ-380 
description: In China,See World.
url: http://mqsh.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/img/avatar.JPG
favicon: /assets/img/avatar.JPG
>>>>>>> origin/master
